# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('translation', models.TextField(null=True)),
                ('part_of_speech_id', models.SmallIntegerField(null=True)),
                ('past_form', models.CharField(max_length=50, null=True)),
                ('participle_form', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
